function [ ret ] = get_report_datatype(  )
%GET_REPORT_DATATYPE For each model we save report in this format
%   Detailed explanation goes here

    ret = struct(...
        'm_id', [],...
        'skipped', false,...
        'opens', false,...
        'timedout', false,...
        'simdur', [],...
        'exception', false,...
        'exception_msg', [],...
        'exception_ob', [],...
        'sys', [],...
        'blocks', [],...
        'numzerocov', [],...
        'stoptime_changed', [],...
        'loc', [],... % Actual location. Inaccurate for EXPLORE 
        'loc_input', [],... % model path which was provided as input.
        'duration', []);

end

