function [ ret ] = get_report_datatype( exp_no, m_id )
%GET_REPORT_DATATYPE Report for experimenting with a single model
%   Detailed explanation goes here

ret = struct('exp_no', exp_no,...
    'm_id', m_id,...
    'opens', [],...
    'exception', [],... % bool
    'exception_id', [],...
    'mutants', [],...
    'exception_ob', []);

end

