function [source_blocktypes,source_masktypes] = get_source_blocks()
%GET_SOURCE_BLOCKS Get blocks from source library
%   First get list of all sources
% x = cps.slsf.getBlockSpec('Sources', true);
% Blocks who have unique BlockType
% source_blocktypes = x{~strcmp(x.BlockType, 'SubSystem'),'BlockType'}
% Blocks who don't have unique BlockType
% source_masktypes = x{strcmp(x.BlockType, 'SubSystem'), 'MaskType')
% Turns out all of the latest can be uniquely identified using the MaskType
% parameter.
% To check with other libraries, run getBlockSpec with a list of libraries
% whose blocks may be in your model corpus.
% say x has this output. Now run
% x(cellfun(@(p)any(strcmp(p, source_masktypes)),x.MaskType),:)
% where source_masktypes is the cell array. Make sure all of the blocks
% returned are from the Sources library

% datafile = 'sources18a';
% 
% read_data = load([utility.dirname(mfilename('fullpath')) filesep datafile]);
% 
% sources_blocktypes = read_data.sources_blocktypes;
% sources_masktypes = read_data.sources_masktypes;

%  Generated by MATLAB on 13-Feb-2019 12:07:41
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
                             

source_blocktypes = cell(14, 1);
source_blocktypes{1,1} = 'Inport';
source_blocktypes{2,1} = 'Clock';
source_blocktypes{3,1} = 'Constant';
source_blocktypes{4,1} = 'DigitalClock';
source_blocktypes{5,1} = 'FromWorkspace';
source_blocktypes{6,1} = 'FromFile';
source_blocktypes{7,1} = 'FromSpreadsheet';
source_blocktypes{8,1} = 'Ground';
source_blocktypes{9,1} = 'DiscretePulseGenerator';
source_blocktypes{10,1} = 'RandomNumber';
source_blocktypes{11,1} = 'SignalGenerator';
source_blocktypes{12,1} = 'Sin';
source_blocktypes{13,1} = 'Step';
source_blocktypes{14,1} = 'UniformRandomNumber';

source_masktypes = cell(12, 1);
source_masktypes{1,1} = 'Band-Limited White Noise.';
source_masktypes{2,1} = 'chirp';
source_masktypes{3,1} = 'Counter Free-Running';
source_masktypes{4,1} = 'Counter Limited';
source_masktypes{5,1} = 'Enumerated Constant';
source_masktypes{6,1} = 'Ramp';
source_masktypes{7,1} = 'Repeating table';
source_masktypes{8,1} = 'Repeating Sequence Interpolated';
source_masktypes{9,1} = 'Repeating Sequence Stair';
source_masktypes{10,1} = 'Sigbuilder block';
source_masktypes{11,1} = 'SignalEditor';
source_masktypes{12,1} = 'WaveformGenerator';

end

